"""empty message

Revision ID: a9c728c12504
Revises: 
Create Date: 2025-05-12 18:47:05.264556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c728c12504'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('client',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('stuff',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.drop_constraint('request_client_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.create_foreign_key('request_client_fkey', 'users', ['client'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('stuff',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('client',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
